module Evergreen.Migrate.V23 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Browser.Dom
import Dict
import Element
import Evergreen.V23.Types
import Evergreen.V23.Types.Password
import Evergreen.V8.Password
import Evergreen.V8.Types
import Lamdera.Migrations exposing (..)
import List
import Task


frontendModel : Evergreen.V8.Types.FrontendModel -> ModelMigration Evergreen.V23.Types.FrontendModel Evergreen.V23.Types.FrontendMsg
frontendModel old =
    ModelMigrated
        ( migrate_Types_FrontendModel old
        , Browser.Dom.getViewport
            |> Task.perform
                (\{ viewport } ->
                    Evergreen.V23.Types.Resize
                        (floor viewport.width)
                        (floor viewport.height)
                )
        )


backendModel : Evergreen.V8.Types.BackendModel -> ModelMigration Evergreen.V23.Types.BackendModel Evergreen.V23.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V8.Types.FrontendMsg -> MsgMigration Evergreen.V23.Types.FrontendMsg Evergreen.V23.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V8.Types.ToBackend -> MsgMigration Evergreen.V23.Types.ToBackend Evergreen.V23.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V8.Types.BackendMsg -> MsgMigration Evergreen.V23.Types.BackendMsg Evergreen.V23.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V8.Types.ToFrontend -> MsgMigration Evergreen.V23.Types.ToFrontend Evergreen.V23.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V8.Types.FrontendModel -> Evergreen.V23.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , inner = old.inner |> migrate_Types_InnerModel
    , deviceClass = Element.Desktop
    }


migrate_Types_AdminMsg : Evergreen.V8.Types.AdminMsg -> Evergreen.V23.Types.AdminMsg
migrate_Types_AdminMsg old =
    case old of
        Evergreen.V8.Types.CreatePrepare p0 ->
            Evergreen.V23.Types.CreatePrepare p0

        Evergreen.V8.Types.CreateDo p0 ->
            Evergreen.V23.Types.CreateDo p0

        Evergreen.V8.Types.UpdatePrepare p0 p1 p2 p3 ->
            Evergreen.V23.Types.UpdatePrepare p0 p1 p2 p3

        Evergreen.V8.Types.UpdateDo p0 p1 ->
            Evergreen.V23.Types.UpdateDo p0 (p1 |> migrate_Types_CYOA)

        Evergreen.V8.Types.RenamePrepare p0 p1 ->
            Evergreen.V23.Types.RenamePrepare p0 p1

        Evergreen.V8.Types.RenameDo p0 p1 ->
            Evergreen.V23.Types.RenameDo p0 p1

        Evergreen.V8.Types.DeletePrepare p0 ->
            Evergreen.V23.Types.DeletePrepare p0

        Evergreen.V8.Types.DeleteDo p0 ->
            Evergreen.V23.Types.DeleteDo p0

        Evergreen.V8.Types.List ->
            Evergreen.V23.Types.List


migrate_Types_CYOA : Evergreen.V8.Types.CYOA -> Evergreen.V23.Types.CYOA
migrate_Types_CYOA old =
    old |> List.map migrate_Types_Section


migrate_Types_Choices : Evergreen.V8.Types.Choices -> Evergreen.V23.Types.Choices
migrate_Types_Choices old =
    case old of
        Evergreen.V8.Types.Tiered p0 ->
            Evergreen.V23.Types.Tiered (p0 |> Dict.map (\k -> migrate_Types_Tier))

        Evergreen.V8.Types.Simple p0 ->
            Evergreen.V23.Types.Simple p0


migrate_Types_FrontendMsg : Evergreen.V8.Types.FrontendMsg -> Evergreen.V23.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V8.Types.ChooseTier p0 p1 ->
            Evergreen.V23.Types.ChooseTier p0 (p1 |> Maybe.map migrate_Types_Tier)

        Evergreen.V8.Types.UrlChange p0 ->
            Evergreen.V23.Types.UrlChange p0

        Evergreen.V8.Types.UrlRequest p0 ->
            Evergreen.V23.Types.UrlRequest p0

        Evergreen.V8.Types.ToggleKind p0 ->
            Evergreen.V23.Types.ToggleKind (p0 |> migrate_Types_Kind)

        Evergreen.V8.Types.Password p0 ->
            Evergreen.V23.Types.Password (p0 |> migrate_Types_Password_Password)

        Evergreen.V8.Types.TryLogin ->
            Evergreen.V23.Types.TryLogin

        Evergreen.V8.Types.AdminMsg p0 ->
            Evergreen.V23.Types.AdminMsg (p0 |> migrate_Types_AdminMsg)


migrate_Types_InnerAdminModel : Evergreen.V8.Types.InnerAdminModel -> Evergreen.V23.Types.InnerAdminModel
migrate_Types_InnerAdminModel old =
    case old of
        Evergreen.V8.Types.Listing ->
            Evergreen.V23.Types.Listing

        Evergreen.V8.Types.Creating p0 ->
            Evergreen.V23.Types.Creating p0

        Evergreen.V8.Types.Editing p0 p1 p2 p3 ->
            Evergreen.V23.Types.Editing p0 p1 p2 p3

        Evergreen.V8.Types.Deleting p0 ->
            Evergreen.V23.Types.Deleting p0

        Evergreen.V8.Types.Renaming p0 p1 ->
            Evergreen.V23.Types.Renaming p0 p1


migrate_Types_InnerModel : Evergreen.V8.Types.InnerModel -> Evergreen.V23.Types.InnerModel
migrate_Types_InnerModel old =
    case old of
        Evergreen.V8.Types.Homepage ->
            Evergreen.V23.Types.Homepage

        Evergreen.V8.Types.Loading p0 p1 ->
            Evergreen.V23.Types.Loading p0 (p1 |> migrate_Types_Choices)

        Evergreen.V8.Types.NotFound p0 ->
            Evergreen.V23.Types.NotFound p0

        Evergreen.V8.Types.Login p0 ->
            Evergreen.V23.Types.Login
                { password = p0.password |> migrate_Types_Password_Password
                , loggingIn = p0.loggingIn
                }

        Evergreen.V8.Types.Admin p0 ->
            Evergreen.V23.Types.Admin
                { password = p0.password |> migrate_Types_Password_Password
                , cyoas = p0.cyoas |> Dict.map (\k -> migrate_Types_CYOA)
                , inner = p0.inner |> migrate_Types_InnerAdminModel
                }

        Evergreen.V8.Types.Loaded p0 ->
            Evergreen.V23.Types.Loaded
                { cyoaId = p0.cyoaId
                , choices = p0.choices |> migrate_Types_Choices
                , data = p0.data |> migrate_Types_CYOA
                }


migrate_Types_Kind : Evergreen.V8.Types.Kind -> Evergreen.V23.Types.Kind
migrate_Types_Kind old =
    case old of
        Evergreen.V8.Types.TieredKind ->
            Evergreen.V23.Types.TieredKind

        Evergreen.V8.Types.SimpleKind ->
            Evergreen.V23.Types.SimpleKind


migrate_Types_Password_Password : Evergreen.V8.Password.Password -> Evergreen.V23.Types.Password.Password
migrate_Types_Password_Password old =
    case old of
        Evergreen.V8.Password.Password p0 ->
            Evergreen.V23.Types.Password.Password p0


migrate_Types_Power : Evergreen.V8.Types.Power -> Evergreen.V23.Types.Power
migrate_Types_Power old =
    { label = old.label
    , id = old.id
    , cost = old.cost
    , replaces = old.replaces
    , requires = old.requires |> List.map migrate_Types_Requirement
    , description = old.description
    }


migrate_Types_Requirement : Evergreen.V8.Types.Requirement -> Evergreen.V23.Types.Requirement
migrate_Types_Requirement old =
    case old of
        Evergreen.V8.Types.Requirement p0 ->
            Evergreen.V23.Types.Requirement p0

        Evergreen.V8.Types.AtLeastXOf p0 p1 ->
            Evergreen.V23.Types.AtLeastXOf p0 (p1 |> List.map migrate_Types_Requirement)


migrate_Types_Section : Evergreen.V8.Types.Section -> Evergreen.V23.Types.Section
migrate_Types_Section old =
    { name = old.name
    , description = old.description
    , powers = old.powers |> List.map migrate_Types_Power
    }


migrate_Types_Tier : Evergreen.V8.Types.Tier -> Evergreen.V23.Types.Tier
migrate_Types_Tier old =
    case old of
        Evergreen.V8.Types.S ->
            Evergreen.V23.Types.S

        Evergreen.V8.Types.A ->
            Evergreen.V23.Types.A

        Evergreen.V8.Types.B ->
            Evergreen.V23.Types.B

        Evergreen.V8.Types.C ->
            Evergreen.V23.Types.C

        Evergreen.V8.Types.D ->
            Evergreen.V23.Types.D

        Evergreen.V8.Types.F ->
            Evergreen.V23.Types.F
